#!/usr/bin/env bash
# Generates .env and starts docker-compose.yml (repository root).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"
COMPOSE_FILE="$ROOT/docker-compose.yml"

WRITE_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --write-env-only) WRITE_ONLY=true ;;
    -h|--help)
      echo "Usage: $0 [--write-env-only]"
      echo "  --write-env-only  generate .env only (for Portainer)"
      echo "  Set OKTOPUS_API_HOST / OKTOPUS_API_PORT in the environment to skip prompts."
      exit 0
      ;;
  esac
done

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

detect_api_host() {
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
  fi
  if [[ -z "$ip" ]]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  if [[ -n "$ip" ]]; then
    echo "$ip"
  else
    echo "127.0.0.1"
  fi
}

prompt_api_host() {
  if [[ -n "${OKTOPUS_API_HOST:-}" ]]; then
    echo "$OKTOPUS_API_HOST"
    return
  fi
  local suggested reply
  suggested="$(detect_api_host)"
  echo ""
  echo "API host (server IP for browser URL and CORS)."
  echo "Use a static IP (DHCP reservation or fixed address) for stable operation."
  read -r -p "API host [${suggested}]: " reply
  if [[ -z "${reply// }" ]]; then
    echo "$suggested"
  else
    echo "$reply"
  fi
}

prompt_api_port() {
  if [[ -n "${OKTOPUS_API_PORT:-}" ]]; then
    echo "$OKTOPUS_API_PORT"
    return
  fi
  local suggested="8000" reply
  echo "Public HTTP port (nginx). Prefer 8000 on Docker Desktop (port 80 is often taken or restricted)."
  read -r -p "API port [${suggested}]: " reply
  if [[ -z "${reply// }" ]]; then
    echo "$suggested"
  else
    echo "$reply"
  fi
}

read_env_var() {
  local key="$1" file="$2"
  if [[ -f "$file" ]]; then
    grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2-
  fi
}

docker_volume_exists() {
  docker volume inspect "$1" >/dev/null 2>&1
}

write_env() {
  local prev_pg_pass prev_ch_pass prev_api_internal
  prev_pg_pass="$(read_env_var POSTGRES_PASSWORD "$ENV_FILE")"
  prev_ch_pass="$(read_env_var CLICKHOUSE_PASSWORD "$ENV_FILE")"
  prev_api_internal="$(read_env_var OKTOPUS_API_INTERNAL_PORT "$ENV_FILE")"
  rm -f "$ENV_FILE"

  local pg_user="${POSTGRES_USER:-oktopus}"
  local pg_db="${POSTGRES_DB:-oktopus}"
  local ch_db="${CLICKHOUSE_DATABASE:-oktopus}"
  local ch_user="${CLICKHOUSE_USER:-oktopus}"
  local admin_user="${OKTOPUS_ADMIN_USERNAME:-admin}"
  local pg_host_port="${POSTGRES_HOST_PORT:-5432}"
  # Not 8177/9054 — those are docker-compose.dev.yml on the same host.
  local ch_http_port="${CLICKHOUSE_HTTP_HOST_PORT:-18177}"
  local ch_native_port="${CLICKHOUSE_NATIVE_HOST_PORT:-19054}"

  local pg_pass ch_pass admin_pass api_host api_port api_internal_port cors
  if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
    pg_pass="$POSTGRES_PASSWORD"
  elif docker_volume_exists oktopus-local_oktopus_local_pg && [[ -n "$prev_pg_pass" ]]; then
    pg_pass="$prev_pg_pass"
    echo "Keeping Postgres password (existing Docker volume)."
  elif docker_volume_exists oktopus-local_oktopus_local_pg; then
    echo "Postgres volume exists but POSTGRES_PASSWORD is unknown. Run: docker compose down -v then stack-up again." >&2
    exit 1
  else
    pg_pass="$(gen_secret)"
  fi
  if [[ -n "${CLICKHOUSE_PASSWORD:-}" ]]; then
    ch_pass="$CLICKHOUSE_PASSWORD"
  elif docker_volume_exists oktopus-local_oktopus_local_ch && [[ -n "$prev_ch_pass" ]]; then
    ch_pass="$prev_ch_pass"
    echo "Keeping ClickHouse password (existing Docker volume)."
  elif docker_volume_exists oktopus-local_oktopus_local_ch; then
    echo "ClickHouse volume exists but CLICKHOUSE_PASSWORD is unknown. Run: docker compose down -v then stack-up again." >&2
    exit 1
  else
    ch_pass="$(gen_secret)"
  fi
  admin_pass="$(gen_secret)"
  api_host="$(prompt_api_host)"
  api_port="$(prompt_api_port)"
  if [[ -n "${OKTOPUS_API_INTERNAL_PORT:-}" ]]; then
    api_internal_port="$OKTOPUS_API_INTERNAL_PORT"
  elif [[ -n "$prev_api_internal" ]]; then
    api_internal_port="$prev_api_internal"
  else
    api_internal_port="18002"
  fi
  cors="http://${api_host}:${api_port}"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/stack-up.sh — do not commit.
POSTGRES_USER=${pg_user}
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=${pg_db}
POSTGRES_HOST_PORT=${pg_host_port}

CLICKHOUSE_DATABASE=${ch_db}
CLICKHOUSE_USER=${ch_user}
CLICKHOUSE_PASSWORD=${ch_pass}
CLICKHOUSE_HTTP_HOST_PORT=${ch_http_port}
CLICKHOUSE_NATIVE_HOST_PORT=${ch_native_port}
CLICKHOUSE_ADDR=127.0.0.1:${ch_native_port}

DATABASE_URL=postgres://${pg_user}:${pg_pass}@127.0.0.1:${pg_host_port}/${pg_db}?sslmode=disable

OKTOPUS_API_HOST=${api_host}
OKTOPUS_API_PORT=${api_port}
OKTOPUS_API_INTERNAL_PORT=${api_internal_port}
OKTOPUS_API_UPSTREAM_HOST=host.docker.internal
OKTOPUS_CORS_ORIGINS=${cors}
OKTOPUS_ADMIN_USERNAME=${admin_user}
OKTOPUS_ADMIN_PASSWORD=${admin_pass}
EOF
  chmod 600 "$ENV_FILE" 2>/dev/null || true
}

echo "Note: .env is recreated each run; DB passwords are kept when Docker volumes already exist."
write_env
echo "Wrote $ENV_FILE"

if [[ "$WRITE_ONLY" == true ]]; then
  echo "Env only; copy variables to Portainer or run without --write-env-only to start stack."
  exit 0
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose not found." >&2
  exit 1
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up --build -d

admin_user="$(grep -E '^OKTOPUS_ADMIN_USERNAME=' "$ENV_FILE" | cut -d= -f2-)"
admin_pass="$(grep -E '^OKTOPUS_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
api_host="$(grep -E '^OKTOPUS_API_HOST=' "$ENV_FILE" | cut -d= -f2-)"
api_port="$(grep -E '^OKTOPUS_API_PORT=' "$ENV_FILE" | cut -d= -f2-)"

echo ""
cat <<'EOF'
 ██████╗ ██╗  ██╗████████╗ ██████╗ ██████╗ ██╗   ██╗███████╗
██╔═══██╗██║ ██╔╝╚══██╔══╝██╔═══██╗██╔══██╗██║   ██║██╔════╝
██║   ██║█████╔╝    ██║   ██║   ██║██████╔╝██║   ██║███████╗
██║   ██║██╔═██╗    ██║   ██║   ██║██╔═══╝ ██║   ██║╚════██║
╚██████╔╝██║  ██╗   ██║   ╚██████╔╝██║     ╚██████╔╝███████║
 ╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝      ╚═════╝ ╚══════╝
EOF
echo ""
echo "========== OKTOPUS =========="
echo "UI:       http://${api_host}:${api_port}/"
echo "Login:    ${admin_user}"
echo "Password: ${admin_pass}"
echo "Env file: ${ENV_FILE}"
echo "=============================="
echo ""
