param(
    [Parameter(Mandatory = $true)]
    [string] $EnvFile
)

$ErrorActionPreference = 'Stop'

function New-HexSecret {
    $bytes = New-Object byte[] 16
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return ([BitConverter]::ToString($bytes) -replace '-', '').ToLower()
}

function Get-SuggestedApiHost {
    $addr = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object { $_.IPAddress -notlike '127.*' -and $_.PrefixOrigin -ne 'WellKnown' } |
        Select-Object -First 1 -ExpandProperty IPAddress
    if ($addr) { return $addr }
    return '127.0.0.1'
}

function Get-ApiHostInteractive {
    if ($env:OKTOPUS_API_HOST) {
        return $env:OKTOPUS_API_HOST.Trim()
    }
    $suggested = Get-SuggestedApiHost
    Write-Host ''
    Write-Host 'API host (server IP for browser URL and CORS).'
    Write-Host 'Use a static IP (DHCP reservation or fixed address) for stable operation.'
    $answer = Read-Host "API host [$suggested]"
    if ([string]::IsNullOrWhiteSpace($answer)) {
        return $suggested
    }
    return $answer.Trim()
}

function Get-ApiPortInteractive {
    if ($env:OKTOPUS_API_PORT) {
        return $env:OKTOPUS_API_PORT.Trim()
    }
    $suggested = '8000'
    Write-Host 'Public HTTP port (nginx). Port 80 often conflicts on Windows; 8000 is safer for Docker Desktop.'
    $answer = Read-Host "API port [$suggested]"
    if ([string]::IsNullOrWhiteSpace($answer)) {
        return $suggested
    }
    return $answer.Trim()
}

function Read-EnvFileValue {
    param([string] $Path, [string] $Key)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -match "^$Key=(.*)$") {
            return $Matches[1]
        }
    }
    return $null
}

function Test-DockerVolumeExists {
    param([string] $Name)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    $null = docker volume inspect $Name 2>&1
    $ok = $LASTEXITCODE -eq 0
    $ErrorActionPreference = $prev
    return $ok
}

function Test-AnyDockerVolumeExists {
    param([string[]] $Names)
    foreach ($n in $Names) {
        if (Test-DockerVolumeExists $n) { return $true }
    }
    return $false
}

$composePgVol = 'oktopus-onprem_oktopus_onprem_pg'
$composeChVol = 'oktopus-onprem_oktopus_onprem_ch'
$legacyPgVol = 'oktopus-local_oktopus_local_pg'
$legacyChVol = 'oktopus-local_oktopus_local_ch'

$prevPgPass = Read-EnvFileValue -Path $EnvFile -Key 'POSTGRES_PASSWORD'
$prevChPass = Read-EnvFileValue -Path $EnvFile -Key 'CLICKHOUSE_PASSWORD'
$prevApiInternalPort = Read-EnvFileValue -Path $EnvFile -Key 'OKTOPUS_API_INTERNAL_PORT'

if (Test-Path -LiteralPath $EnvFile) {
    Remove-Item -LiteralPath $EnvFile -Force
}

$pgUser = if ($env:POSTGRES_USER) { $env:POSTGRES_USER } else { 'oktopus' }
$pgDb = if ($env:POSTGRES_DB) { $env:POSTGRES_DB } else { 'oktopus' }
$chDb = if ($env:CLICKHOUSE_DATABASE) { $env:CLICKHOUSE_DATABASE } else { 'oktopus' }
$chUser = if ($env:CLICKHOUSE_USER) { $env:CLICKHOUSE_USER } else { 'oktopus' }
$adminUser = if ($env:OKTOPUS_ADMIN_USERNAME) { $env:OKTOPUS_ADMIN_USERNAME } else { 'admin' }
$pgHostPort = if ($env:POSTGRES_HOST_PORT) { $env:POSTGRES_HOST_PORT } else { '5432' }
$chHttpPort = if ($env:CLICKHOUSE_HTTP_HOST_PORT) { $env:CLICKHOUSE_HTTP_HOST_PORT } else { '18177' }
$chNativePort = if ($env:CLICKHOUSE_NATIVE_HOST_PORT) { $env:CLICKHOUSE_NATIVE_HOST_PORT } else { '19054' }

if ($env:POSTGRES_PASSWORD) {
    $pgPass = $env:POSTGRES_PASSWORD.Trim()
} elseif ((Test-AnyDockerVolumeExists @($composePgVol, $legacyPgVol)) -and $prevPgPass) {
    $pgPass = $prevPgPass
    Write-Host 'Keeping Postgres password (existing Docker volume).'
} elseif (Test-AnyDockerVolumeExists @($composePgVol, $legacyPgVol)) {
    Write-Error 'Postgres volume exists but POSTGRES_PASSWORD is unknown. Run: docker compose -f docker-compose.desktop.yml down -v then stack-up again.'
    exit 1
} else {
    $pgPass = New-HexSecret
}

if ($env:CLICKHOUSE_PASSWORD) {
    $chPass = $env:CLICKHOUSE_PASSWORD.Trim()
} elseif ((Test-AnyDockerVolumeExists @($composeChVol, $legacyChVol)) -and $prevChPass) {
    $chPass = $prevChPass
    Write-Host 'Keeping ClickHouse password (existing Docker volume).'
} elseif (Test-AnyDockerVolumeExists @($composeChVol, $legacyChVol)) {
    Write-Error 'ClickHouse volume exists but CLICKHOUSE_PASSWORD is unknown. Run: docker compose -f docker-compose.desktop.yml down -v then stack-up again.'
    exit 1
} else {
    $chPass = New-HexSecret
}

$adminPass = New-HexSecret
$apiHost = Get-ApiHostInteractive
$apiPort = Get-ApiPortInteractive
if ($env:OKTOPUS_API_INTERNAL_PORT) {
    $apiInternalPort = $env:OKTOPUS_API_INTERNAL_PORT.Trim()
} elseif ($prevApiInternalPort) {
    $apiInternalPort = $prevApiInternalPort
} else {
    $apiInternalPort = '18002'
}
$cors = "http://${apiHost}:${apiPort}"

$content = @"
# Generated by scripts/stack-up.bat — do not commit.
POSTGRES_USER=$pgUser
POSTGRES_PASSWORD=$pgPass
POSTGRES_DB=$pgDb
POSTGRES_HOST_PORT=$pgHostPort

CLICKHOUSE_DATABASE=$chDb
CLICKHOUSE_USER=$chUser
CLICKHOUSE_PASSWORD=$chPass
CLICKHOUSE_HTTP_HOST_PORT=$chHttpPort
CLICKHOUSE_NATIVE_HOST_PORT=$chNativePort
CLICKHOUSE_ADDR=clickhouse:9000

DATABASE_URL=postgres://${pgUser}:${pgPass}@postgres:5432/${pgDb}?sslmode=disable

OKTOPUS_API_HOST=$apiHost
OKTOPUS_API_PORT=$apiPort
OKTOPUS_API_INTERNAL_PORT=$apiInternalPort
OKTOPUS_API_UPSTREAM_HOST=oktopus
OKTOPUS_CORS_ORIGINS=$cors
OKTOPUS_ADMIN_USERNAME=$adminUser
OKTOPUS_ADMIN_PASSWORD=$adminPass
"@

$dir = Split-Path -Parent $EnvFile
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($EnvFile, $content + [Environment]::NewLine, $utf8)
