// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProxyAclList struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	ListType            string             `json:"list_type"`
	Body                string             `json:"body"`
	SourceMode          string             `json:"source_mode"`
	SourceUrl           string             `json:"source_url"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ProxyAclPolicy struct {
	ID         uuid.UUID          `json:"id"`
	ConfigText string             `json:"config_text"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProxyInspectRule struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Script    string             `json:"script"`
	Action    int16              `json:"action"`
	Enabled   bool               `json:"enabled"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProxySetting struct {
	ID                     uuid.UUID          `json:"id"`
	ProxyEnabled           bool               `json:"proxy_enabled"`
	Listen                 string             `json:"listen"`
	ConnectMode            string             `json:"connect_mode"`
	CaCertPath             string             `json:"ca_cert_path"`
	CaKeyPath              string             `json:"ca_key_path"`
	AuthEnabled            bool               `json:"auth_enabled"`
	AuthStaticUsers        string             `json:"auth_static_users"`
	AuthRealm              string             `json:"auth_realm"`
	AuthBackend            string             `json:"auth_backend"`
	AuthCacheTtlMinutes    int64              `json:"auth_cache_ttl_minutes"`
	LdapUrl                string             `json:"ldap_url"`
	LdapBaseDn             string             `json:"ldap_base_dn"`
	LdapBindDn             string             `json:"ldap_bind_dn"`
	LdapBindPassword       string             `json:"ldap_bind_password"`
	AccessLogRetentionDays int32              `json:"access_log_retention_days"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
