// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_inspect_rules.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProxyInspectRules = `-- name: CountProxyInspectRules :one
SELECT count(*)::bigint AS count FROM proxy_inspect_rules
`

func (q *Queries) CountProxyInspectRules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProxyInspectRules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllProxyInspectRules = `-- name: DeleteAllProxyInspectRules :exec
DELETE FROM proxy_inspect_rules
`

func (q *Queries) DeleteAllProxyInspectRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllProxyInspectRules)
	return err
}

const deleteProxyInspectRulesExcept = `-- name: DeleteProxyInspectRulesExcept :exec
DELETE FROM proxy_inspect_rules
WHERE cardinality($1::uuid[]) = 0
   OR NOT (id = ANY ($1::uuid[]))
`

func (q *Queries) DeleteProxyInspectRulesExcept(ctx context.Context, keepIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProxyInspectRulesExcept, keepIds)
	return err
}

const getProxyInspectRule = `-- name: GetProxyInspectRule :one
SELECT
    id,
    name,
    script,
    action,
    enabled,
    sort_order,
    created_at,
    updated_at
FROM proxy_inspect_rules
WHERE id = $1
`

func (q *Queries) GetProxyInspectRule(ctx context.Context, id uuid.UUID) (ProxyInspectRule, error) {
	row := q.db.QueryRow(ctx, getProxyInspectRule, id)
	var i ProxyInspectRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Script,
		&i.Action,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProxyInspectRule = `-- name: InsertProxyInspectRule :one
INSERT INTO proxy_inspect_rules (
    id,
    name,
    script,
    action,
    enabled,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    name,
    script,
    action,
    enabled,
    sort_order,
    created_at,
    updated_at
`

type InsertProxyInspectRuleParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Script    string    `json:"script"`
	Action    int16     `json:"action"`
	Enabled   bool      `json:"enabled"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) InsertProxyInspectRule(ctx context.Context, arg InsertProxyInspectRuleParams) (ProxyInspectRule, error) {
	row := q.db.QueryRow(ctx, insertProxyInspectRule,
		arg.ID,
		arg.Name,
		arg.Script,
		arg.Action,
		arg.Enabled,
		arg.SortOrder,
	)
	var i ProxyInspectRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Script,
		&i.Action,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyInspectRules = `-- name: ListProxyInspectRules :many
SELECT
    id,
    name,
    script,
    action,
    enabled,
    sort_order,
    created_at,
    updated_at
FROM proxy_inspect_rules
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProxyInspectRules(ctx context.Context) ([]ProxyInspectRule, error) {
	rows, err := q.db.Query(ctx, listProxyInspectRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyInspectRule{}
	for rows.Next() {
		var i ProxyInspectRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Script,
			&i.Action,
			&i.Enabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyInspectRulesSummary = `-- name: ListProxyInspectRulesSummary :many
SELECT
    id,
    name,
    action,
    enabled,
    sort_order,
    length(script) AS script_length,
    created_at,
    updated_at
FROM proxy_inspect_rules
ORDER BY sort_order ASC, created_at ASC
`

type ListProxyInspectRulesSummaryRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Action       int16              `json:"action"`
	Enabled      bool               `json:"enabled"`
	SortOrder    int32              `json:"sort_order"`
	ScriptLength float64            `json:"script_length"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProxyInspectRulesSummary(ctx context.Context) ([]ListProxyInspectRulesSummaryRow, error) {
	rows, err := q.db.Query(ctx, listProxyInspectRulesSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyInspectRulesSummaryRow{}
	for rows.Next() {
		var i ListProxyInspectRulesSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.Enabled,
			&i.SortOrder,
			&i.ScriptLength,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProxyInspectRule = `-- name: UpsertProxyInspectRule :one
INSERT INTO proxy_inspect_rules (
    id,
    name,
    script,
    action,
    enabled,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    script = EXCLUDED.script,
    action = EXCLUDED.action,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = now()
RETURNING
    id,
    name,
    script,
    action,
    enabled,
    sort_order,
    created_at,
    updated_at
`

type UpsertProxyInspectRuleParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Script    string    `json:"script"`
	Action    int16     `json:"action"`
	Enabled   bool      `json:"enabled"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpsertProxyInspectRule(ctx context.Context, arg UpsertProxyInspectRuleParams) (ProxyInspectRule, error) {
	row := q.db.QueryRow(ctx, upsertProxyInspectRule,
		arg.ID,
		arg.Name,
		arg.Script,
		arg.Action,
		arg.Enabled,
		arg.SortOrder,
	)
	var i ProxyInspectRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Script,
		&i.Action,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
