// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_settings.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getProxySettings = `-- name: GetProxySettings :one
SELECT
    id,
    proxy_enabled,
    listen,
    connect_mode,
    ca_cert_path,
    ca_key_path,
    auth_enabled,
    auth_static_users,
    auth_realm,
    auth_backend,
    auth_cache_ttl_minutes,
    ldap_url,
    ldap_base_dn,
    ldap_bind_dn,
    ldap_bind_password,
    access_log_retention_days,
    created_at,
    updated_at
FROM proxy_settings
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetProxySettings(ctx context.Context) (ProxySetting, error) {
	row := q.db.QueryRow(ctx, getProxySettings)
	var i ProxySetting
	err := row.Scan(
		&i.ID,
		&i.ProxyEnabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProxySettings = `-- name: InsertProxySettings :one
INSERT INTO proxy_settings (
    id,
    proxy_enabled,
    listen,
    connect_mode,
    ca_cert_path,
    ca_key_path,
    auth_enabled,
    auth_static_users,
    auth_realm,
    auth_backend,
    auth_cache_ttl_minutes,
    ldap_url,
    ldap_base_dn,
    ldap_bind_dn,
    ldap_bind_password,
    access_log_retention_days
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
RETURNING
    id,
    proxy_enabled,
    listen,
    connect_mode,
    ca_cert_path,
    ca_key_path,
    auth_enabled,
    auth_static_users,
    auth_realm,
    auth_backend,
    auth_cache_ttl_minutes,
    ldap_url,
    ldap_base_dn,
    ldap_bind_dn,
    ldap_bind_password,
    access_log_retention_days,
    created_at,
    updated_at
`

type InsertProxySettingsParams struct {
	ID                     uuid.UUID `json:"id"`
	ProxyEnabled           bool      `json:"proxy_enabled"`
	Listen                 string    `json:"listen"`
	ConnectMode            string    `json:"connect_mode"`
	CaCertPath             string    `json:"ca_cert_path"`
	CaKeyPath              string    `json:"ca_key_path"`
	AuthEnabled            bool      `json:"auth_enabled"`
	AuthStaticUsers        string    `json:"auth_static_users"`
	AuthRealm              string    `json:"auth_realm"`
	AuthBackend            string    `json:"auth_backend"`
	AuthCacheTtlMinutes    int64     `json:"auth_cache_ttl_minutes"`
	LdapUrl                string    `json:"ldap_url"`
	LdapBaseDn             string    `json:"ldap_base_dn"`
	LdapBindDn             string    `json:"ldap_bind_dn"`
	LdapBindPassword       string    `json:"ldap_bind_password"`
	AccessLogRetentionDays int32     `json:"access_log_retention_days"`
}

func (q *Queries) InsertProxySettings(ctx context.Context, arg InsertProxySettingsParams) (ProxySetting, error) {
	row := q.db.QueryRow(ctx, insertProxySettings,
		arg.ID,
		arg.ProxyEnabled,
		arg.Listen,
		arg.ConnectMode,
		arg.CaCertPath,
		arg.CaKeyPath,
		arg.AuthEnabled,
		arg.AuthStaticUsers,
		arg.AuthRealm,
		arg.AuthBackend,
		arg.AuthCacheTtlMinutes,
		arg.LdapUrl,
		arg.LdapBaseDn,
		arg.LdapBindDn,
		arg.LdapBindPassword,
		arg.AccessLogRetentionDays,
	)
	var i ProxySetting
	err := row.Scan(
		&i.ID,
		&i.ProxyEnabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProxyCAPaths = `-- name: UpdateProxyCAPaths :one
UPDATE proxy_settings
SET
    ca_cert_path = $2,
    ca_key_path = $3,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    proxy_enabled,
    listen,
    connect_mode,
    ca_cert_path,
    ca_key_path,
    auth_enabled,
    auth_static_users,
    auth_realm,
    auth_backend,
    auth_cache_ttl_minutes,
    ldap_url,
    ldap_base_dn,
    ldap_bind_dn,
    ldap_bind_password,
    access_log_retention_days,
    created_at,
    updated_at
`

type UpdateProxyCAPathsParams struct {
	ID         uuid.UUID `json:"id"`
	CaCertPath string    `json:"ca_cert_path"`
	CaKeyPath  string    `json:"ca_key_path"`
}

func (q *Queries) UpdateProxyCAPaths(ctx context.Context, arg UpdateProxyCAPathsParams) (ProxySetting, error) {
	row := q.db.QueryRow(ctx, updateProxyCAPaths, arg.ID, arg.CaCertPath, arg.CaKeyPath)
	var i ProxySetting
	err := row.Scan(
		&i.ID,
		&i.ProxyEnabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProxySettings = `-- name: UpdateProxySettings :one
UPDATE proxy_settings
SET
    proxy_enabled = $2,
    listen = $3,
    connect_mode = $4,
    ca_cert_path = $5,
    ca_key_path = $6,
    auth_enabled = $7,
    auth_static_users = $8,
    auth_realm = $9,
    auth_backend = $10,
    auth_cache_ttl_minutes = $11,
    ldap_url = $12,
    ldap_base_dn = $13,
    ldap_bind_dn = $14,
    ldap_bind_password = $15,
    access_log_retention_days = $16,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    proxy_enabled,
    listen,
    connect_mode,
    ca_cert_path,
    ca_key_path,
    auth_enabled,
    auth_static_users,
    auth_realm,
    auth_backend,
    auth_cache_ttl_minutes,
    ldap_url,
    ldap_base_dn,
    ldap_bind_dn,
    ldap_bind_password,
    access_log_retention_days,
    created_at,
    updated_at
`

type UpdateProxySettingsParams struct {
	ID                     uuid.UUID `json:"id"`
	ProxyEnabled           bool      `json:"proxy_enabled"`
	Listen                 string    `json:"listen"`
	ConnectMode            string    `json:"connect_mode"`
	CaCertPath             string    `json:"ca_cert_path"`
	CaKeyPath              string    `json:"ca_key_path"`
	AuthEnabled            bool      `json:"auth_enabled"`
	AuthStaticUsers        string    `json:"auth_static_users"`
	AuthRealm              string    `json:"auth_realm"`
	AuthBackend            string    `json:"auth_backend"`
	AuthCacheTtlMinutes    int64     `json:"auth_cache_ttl_minutes"`
	LdapUrl                string    `json:"ldap_url"`
	LdapBaseDn             string    `json:"ldap_base_dn"`
	LdapBindDn             string    `json:"ldap_bind_dn"`
	LdapBindPassword       string    `json:"ldap_bind_password"`
	AccessLogRetentionDays int32     `json:"access_log_retention_days"`
}

func (q *Queries) UpdateProxySettings(ctx context.Context, arg UpdateProxySettingsParams) (ProxySetting, error) {
	row := q.db.QueryRow(ctx, updateProxySettings,
		arg.ID,
		arg.ProxyEnabled,
		arg.Listen,
		arg.ConnectMode,
		arg.CaCertPath,
		arg.CaKeyPath,
		arg.AuthEnabled,
		arg.AuthStaticUsers,
		arg.AuthRealm,
		arg.AuthBackend,
		arg.AuthCacheTtlMinutes,
		arg.LdapUrl,
		arg.LdapBaseDn,
		arg.LdapBindDn,
		arg.LdapBindPassword,
		arg.AccessLogRetentionDays,
	)
	var i ProxySetting
	err := row.Scan(
		&i.ID,
		&i.ProxyEnabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
