// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_instances.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteProxyInstance = `-- name: DeleteProxyInstance :exec
DELETE FROM proxy_instances WHERE id = $1
`

func (q *Queries) DeleteProxyInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProxyInstance, id)
	return err
}

const getProxyInstance = `-- name: GetProxyInstance :one
SELECT
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order,
    created_at, updated_at
FROM proxy_instances
WHERE id = $1
`

func (q *Queries) GetProxyInstance(ctx context.Context, id uuid.UUID) (ProxyInstance, error) {
	row := q.db.QueryRow(ctx, getProxyInstance, id)
	var i ProxyInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProxyACLPolicyForInstance = `-- name: InsertProxyACLPolicyForInstance :one
INSERT INTO proxy_acl_policy (id, instance_id, config_text)
VALUES ($1, $2, '')
RETURNING id, instance_id, config_text, updated_at
`

type InsertProxyACLPolicyForInstanceParams struct {
	ID         uuid.UUID `json:"id"`
	InstanceID uuid.UUID `json:"instance_id"`
}

func (q *Queries) InsertProxyACLPolicyForInstance(ctx context.Context, arg InsertProxyACLPolicyForInstanceParams) (ProxyAclPolicy, error) {
	row := q.db.QueryRow(ctx, insertProxyACLPolicyForInstance, arg.ID, arg.InstanceID)
	var i ProxyAclPolicy
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ConfigText,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProxyInstance = `-- name: InsertProxyInstance :one
INSERT INTO proxy_instances (
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order,
    created_at, updated_at
`

type InsertProxyInstanceParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	Enabled             bool      `json:"enabled"`
	Listen              string    `json:"listen"`
	ConnectMode         string    `json:"connect_mode"`
	CaCertPath          string    `json:"ca_cert_path"`
	CaKeyPath           string    `json:"ca_key_path"`
	AuthEnabled         bool      `json:"auth_enabled"`
	AuthStaticUsers     string    `json:"auth_static_users"`
	AuthRealm           string    `json:"auth_realm"`
	AuthBackend         string    `json:"auth_backend"`
	AuthCacheTtlMinutes int64     `json:"auth_cache_ttl_minutes"`
	LdapUrl             string    `json:"ldap_url"`
	LdapBaseDn          string    `json:"ldap_base_dn"`
	LdapBindDn          string    `json:"ldap_bind_dn"`
	LdapBindPassword    string    `json:"ldap_bind_password"`
	SortOrder           int32     `json:"sort_order"`
}

func (q *Queries) InsertProxyInstance(ctx context.Context, arg InsertProxyInstanceParams) (ProxyInstance, error) {
	row := q.db.QueryRow(ctx, insertProxyInstance,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Listen,
		arg.ConnectMode,
		arg.CaCertPath,
		arg.CaKeyPath,
		arg.AuthEnabled,
		arg.AuthStaticUsers,
		arg.AuthRealm,
		arg.AuthBackend,
		arg.AuthCacheTtlMinutes,
		arg.LdapUrl,
		arg.LdapBaseDn,
		arg.LdapBindDn,
		arg.LdapBindPassword,
		arg.SortOrder,
	)
	var i ProxyInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyInstances = `-- name: ListProxyInstances :many
SELECT
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order,
    created_at, updated_at
FROM proxy_instances
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProxyInstances(ctx context.Context) ([]ProxyInstance, error) {
	rows, err := q.db.Query(ctx, listProxyInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyInstance{}
	for rows.Next() {
		var i ProxyInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Listen,
			&i.ConnectMode,
			&i.CaCertPath,
			&i.CaKeyPath,
			&i.AuthEnabled,
			&i.AuthStaticUsers,
			&i.AuthRealm,
			&i.AuthBackend,
			&i.AuthCacheTtlMinutes,
			&i.LdapUrl,
			&i.LdapBaseDn,
			&i.LdapBindDn,
			&i.LdapBindPassword,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxyInstance = `-- name: UpdateProxyInstance :one
UPDATE proxy_instances
SET
    name = $2,
    enabled = $3,
    listen = $4,
    connect_mode = $5,
    ca_cert_path = $6,
    ca_key_path = $7,
    auth_enabled = $8,
    auth_static_users = $9,
    auth_realm = $10,
    auth_backend = $11,
    auth_cache_ttl_minutes = $12,
    ldap_url = $13,
    ldap_base_dn = $14,
    ldap_bind_dn = $15,
    ldap_bind_password = $16,
    sort_order = $17,
    updated_at = now()
WHERE id = $1
RETURNING
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order,
    created_at, updated_at
`

type UpdateProxyInstanceParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	Enabled             bool      `json:"enabled"`
	Listen              string    `json:"listen"`
	ConnectMode         string    `json:"connect_mode"`
	CaCertPath          string    `json:"ca_cert_path"`
	CaKeyPath           string    `json:"ca_key_path"`
	AuthEnabled         bool      `json:"auth_enabled"`
	AuthStaticUsers     string    `json:"auth_static_users"`
	AuthRealm           string    `json:"auth_realm"`
	AuthBackend         string    `json:"auth_backend"`
	AuthCacheTtlMinutes int64     `json:"auth_cache_ttl_minutes"`
	LdapUrl             string    `json:"ldap_url"`
	LdapBaseDn          string    `json:"ldap_base_dn"`
	LdapBindDn          string    `json:"ldap_bind_dn"`
	LdapBindPassword    string    `json:"ldap_bind_password"`
	SortOrder           int32     `json:"sort_order"`
}

func (q *Queries) UpdateProxyInstance(ctx context.Context, arg UpdateProxyInstanceParams) (ProxyInstance, error) {
	row := q.db.QueryRow(ctx, updateProxyInstance,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Listen,
		arg.ConnectMode,
		arg.CaCertPath,
		arg.CaKeyPath,
		arg.AuthEnabled,
		arg.AuthStaticUsers,
		arg.AuthRealm,
		arg.AuthBackend,
		arg.AuthCacheTtlMinutes,
		arg.LdapUrl,
		arg.LdapBaseDn,
		arg.LdapBindDn,
		arg.LdapBindPassword,
		arg.SortOrder,
	)
	var i ProxyInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProxyInstanceCAPaths = `-- name: UpdateProxyInstanceCAPaths :one
UPDATE proxy_instances
SET ca_cert_path = $2, ca_key_path = $3, updated_at = now()
WHERE id = $1
RETURNING
    id, name, enabled, listen, connect_mode, ca_cert_path, ca_key_path,
    auth_enabled, auth_static_users, auth_realm, auth_backend, auth_cache_ttl_minutes,
    ldap_url, ldap_base_dn, ldap_bind_dn, ldap_bind_password, sort_order,
    created_at, updated_at
`

type UpdateProxyInstanceCAPathsParams struct {
	ID         uuid.UUID `json:"id"`
	CaCertPath string    `json:"ca_cert_path"`
	CaKeyPath  string    `json:"ca_key_path"`
}

func (q *Queries) UpdateProxyInstanceCAPaths(ctx context.Context, arg UpdateProxyInstanceCAPathsParams) (ProxyInstance, error) {
	row := q.db.QueryRow(ctx, updateProxyInstanceCAPaths, arg.ID, arg.CaCertPath, arg.CaKeyPath)
	var i ProxyInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Listen,
		&i.ConnectMode,
		&i.CaCertPath,
		&i.CaKeyPath,
		&i.AuthEnabled,
		&i.AuthStaticUsers,
		&i.AuthRealm,
		&i.AuthBackend,
		&i.AuthCacheTtlMinutes,
		&i.LdapUrl,
		&i.LdapBaseDn,
		&i.LdapBindDn,
		&i.LdapBindPassword,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
