// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_inspect_rules.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProxyInspectRulesByInstance = `-- name: CountProxyInspectRulesByInstance :one
SELECT count(*)::bigint AS count FROM proxy_inspect_rules WHERE instance_id = $1
`

func (q *Queries) CountProxyInspectRulesByInstance(ctx context.Context, instanceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProxyInspectRulesByInstance, instanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProxyInspectRulesByInstanceExcept = `-- name: DeleteProxyInspectRulesByInstanceExcept :exec
DELETE FROM proxy_inspect_rules
WHERE instance_id = $1
  AND (cardinality($2::uuid[]) = 0 OR NOT (id = ANY ($2::uuid[])))
`

type DeleteProxyInspectRulesByInstanceExceptParams struct {
	InstanceID uuid.UUID   `json:"instance_id"`
	KeepIds    []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeleteProxyInspectRulesByInstanceExcept(ctx context.Context, arg DeleteProxyInspectRulesByInstanceExceptParams) error {
	_, err := q.db.Exec(ctx, deleteProxyInspectRulesByInstanceExcept, arg.InstanceID, arg.KeepIds)
	return err
}

const getProxyInspectRule = `-- name: GetProxyInspectRule :one
SELECT
    id, instance_id, name, script, action, enabled, sort_order, created_at, updated_at
FROM proxy_inspect_rules
WHERE id = $1
`

func (q *Queries) GetProxyInspectRule(ctx context.Context, id uuid.UUID) (ProxyInspectRule, error) {
	row := q.db.QueryRow(ctx, getProxyInspectRule, id)
	var i ProxyInspectRule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Script,
		&i.Action,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyInspectRuleInstanceIDs = `-- name: ListProxyInspectRuleInstanceIDs :many
SELECT DISTINCT instance_id FROM proxy_inspect_rules
`

func (q *Queries) ListProxyInspectRuleInstanceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProxyInspectRuleInstanceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var instance_id uuid.UUID
		if err := rows.Scan(&instance_id); err != nil {
			return nil, err
		}
		items = append(items, instance_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyInspectRulesByInstance = `-- name: ListProxyInspectRulesByInstance :many
SELECT
    id, instance_id, name, script, action, enabled, sort_order, created_at, updated_at
FROM proxy_inspect_rules
WHERE instance_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProxyInspectRulesByInstance(ctx context.Context, instanceID uuid.UUID) ([]ProxyInspectRule, error) {
	rows, err := q.db.Query(ctx, listProxyInspectRulesByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyInspectRule{}
	for rows.Next() {
		var i ProxyInspectRule
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.Script,
			&i.Action,
			&i.Enabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyInspectRulesSummaryByInstance = `-- name: ListProxyInspectRulesSummaryByInstance :many
SELECT
    id, instance_id, name, action, enabled, sort_order,
    length(script) AS script_length, created_at, updated_at
FROM proxy_inspect_rules
WHERE instance_id = $1
ORDER BY sort_order ASC, created_at ASC
`

type ListProxyInspectRulesSummaryByInstanceRow struct {
	ID           uuid.UUID          `json:"id"`
	InstanceID   uuid.UUID          `json:"instance_id"`
	Name         string             `json:"name"`
	Action       int16              `json:"action"`
	Enabled      bool               `json:"enabled"`
	SortOrder    int32              `json:"sort_order"`
	ScriptLength float64            `json:"script_length"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProxyInspectRulesSummaryByInstance(ctx context.Context, instanceID uuid.UUID) ([]ListProxyInspectRulesSummaryByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listProxyInspectRulesSummaryByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyInspectRulesSummaryByInstanceRow{}
	for rows.Next() {
		var i ListProxyInspectRulesSummaryByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.Action,
			&i.Enabled,
			&i.SortOrder,
			&i.ScriptLength,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProxyInspectRule = `-- name: UpsertProxyInspectRule :one
INSERT INTO proxy_inspect_rules (
    id, instance_id, name, script, action, enabled, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE
SET
    instance_id = EXCLUDED.instance_id,
    name = EXCLUDED.name,
    script = EXCLUDED.script,
    action = EXCLUDED.action,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = now()
RETURNING
    id, instance_id, name, script, action, enabled, sort_order, created_at, updated_at
`

type UpsertProxyInspectRuleParams struct {
	ID         uuid.UUID `json:"id"`
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
	Script     string    `json:"script"`
	Action     int16     `json:"action"`
	Enabled    bool      `json:"enabled"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) UpsertProxyInspectRule(ctx context.Context, arg UpsertProxyInspectRuleParams) (ProxyInspectRule, error) {
	row := q.db.QueryRow(ctx, upsertProxyInspectRule,
		arg.ID,
		arg.InstanceID,
		arg.Name,
		arg.Script,
		arg.Action,
		arg.Enabled,
		arg.SortOrder,
	)
	var i ProxyInspectRule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Script,
		&i.Action,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
