// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_acl_policy.sql

package store

import (
	"context"
)

const getProxyACLPolicy = `-- name: GetProxyACLPolicy :one
SELECT id, config_text, updated_at
FROM proxy_acl_policy
ORDER BY id
LIMIT 1
`

func (q *Queries) GetProxyACLPolicy(ctx context.Context) (ProxyAclPolicy, error) {
	row := q.db.QueryRow(ctx, getProxyACLPolicy)
	var i ProxyAclPolicy
	err := row.Scan(&i.ID, &i.ConfigText, &i.UpdatedAt)
	return i, err
}

const upsertProxyACLPolicy = `-- name: UpsertProxyACLPolicy :one
UPDATE proxy_acl_policy
SET config_text = $1, updated_at = now()
WHERE id = (SELECT id FROM proxy_acl_policy ORDER BY id LIMIT 1)
RETURNING id, config_text, updated_at
`

func (q *Queries) UpsertProxyACLPolicy(ctx context.Context, configText string) (ProxyAclPolicy, error) {
	row := q.db.QueryRow(ctx, upsertProxyACLPolicy, configText)
	var i ProxyAclPolicy
	err := row.Scan(&i.ID, &i.ConfigText, &i.UpdatedAt)
	return i, err
}
