// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_acl_policy.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getProxyACLPolicyByInstance = `-- name: GetProxyACLPolicyByInstance :one
SELECT id, instance_id, config_text, updated_at
FROM proxy_acl_policy
WHERE instance_id = $1
`

func (q *Queries) GetProxyACLPolicyByInstance(ctx context.Context, instanceID uuid.UUID) (ProxyAclPolicy, error) {
	row := q.db.QueryRow(ctx, getProxyACLPolicyByInstance, instanceID)
	var i ProxyAclPolicy
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ConfigText,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyACLPolicyInstanceIDs = `-- name: ListProxyACLPolicyInstanceIDs :many
SELECT instance_id FROM proxy_acl_policy
`

func (q *Queries) ListProxyACLPolicyInstanceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProxyACLPolicyInstanceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var instance_id uuid.UUID
		if err := rows.Scan(&instance_id); err != nil {
			return nil, err
		}
		items = append(items, instance_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProxyACLPolicyByInstance = `-- name: UpsertProxyACLPolicyByInstance :one
UPDATE proxy_acl_policy
SET config_text = $2, updated_at = now()
WHERE instance_id = $1
RETURNING id, instance_id, config_text, updated_at
`

type UpsertProxyACLPolicyByInstanceParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	ConfigText string    `json:"config_text"`
}

func (q *Queries) UpsertProxyACLPolicyByInstance(ctx context.Context, arg UpsertProxyACLPolicyByInstanceParams) (ProxyAclPolicy, error) {
	row := q.db.QueryRow(ctx, upsertProxyACLPolicyByInstance, arg.InstanceID, arg.ConfigText)
	var i ProxyAclPolicy
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ConfigText,
		&i.UpdatedAt,
	)
	return i, err
}
