// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_acl_lists.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllProxyACLLists = `-- name: DeleteAllProxyACLLists :exec
DELETE FROM proxy_acl_lists
`

func (q *Queries) DeleteAllProxyACLLists(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllProxyACLLists)
	return err
}

const deleteProxyACLListsExcept = `-- name: DeleteProxyACLListsExcept :exec
DELETE FROM proxy_acl_lists
WHERE cardinality($1::uuid[]) = 0
   OR NOT (id = ANY ($1::uuid[]))
`

func (q *Queries) DeleteProxyACLListsExcept(ctx context.Context, keepIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProxyACLListsExcept, keepIds)
	return err
}

const getProxyACLList = `-- name: GetProxyACLList :one
SELECT id, name, list_type, body, source_mode, source_url, poll_interval_minutes, created_at, updated_at
FROM proxy_acl_lists
WHERE id = $1
`

func (q *Queries) GetProxyACLList(ctx context.Context, id uuid.UUID) (ProxyAclList, error) {
	row := q.db.QueryRow(ctx, getProxyACLList, id)
	var i ProxyAclList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListType,
		&i.Body,
		&i.SourceMode,
		&i.SourceUrl,
		&i.PollIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyACLLists = `-- name: ListProxyACLLists :many
SELECT id, name, list_type, body, source_mode, source_url, poll_interval_minutes, created_at, updated_at
FROM proxy_acl_lists
ORDER BY name, id
`

func (q *Queries) ListProxyACLLists(ctx context.Context) ([]ProxyAclList, error) {
	rows, err := q.db.Query(ctx, listProxyACLLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyAclList{}
	for rows.Next() {
		var i ProxyAclList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListType,
			&i.Body,
			&i.SourceMode,
			&i.SourceUrl,
			&i.PollIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyACLListsByNames = `-- name: ListProxyACLListsByNames :many
SELECT id, name, list_type, body, source_mode, source_url, poll_interval_minutes, created_at, updated_at
FROM proxy_acl_lists
WHERE cardinality($1::text[]) > 0
  AND name = ANY ($1::text[])
ORDER BY name, id
`

func (q *Queries) ListProxyACLListsByNames(ctx context.Context, names []string) ([]ProxyAclList, error) {
	rows, err := q.db.Query(ctx, listProxyACLListsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyAclList{}
	for rows.Next() {
		var i ProxyAclList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListType,
			&i.Body,
			&i.SourceMode,
			&i.SourceUrl,
			&i.PollIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyACLListsSummary = `-- name: ListProxyACLListsSummary :many
SELECT
    id,
    name,
    list_type,
    source_mode,
    source_url,
    poll_interval_minutes,
    created_at,
    updated_at,
    CASE
        WHEN body = '' THEN 0
        ELSE length(body) - length(replace(body, E'\n', '')) + 1
    END::integer AS body_line_count,
    left(
        btrim(replace(split_part(body || E'\n', E'\n', 1), E'\r', ''), E' \t'),
        48
    ) AS body_preview
FROM proxy_acl_lists
ORDER BY name, id
`

type ListProxyACLListsSummaryRow struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	ListType            string             `json:"list_type"`
	SourceMode          string             `json:"source_mode"`
	SourceUrl           string             `json:"source_url"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	BodyLineCount       int32              `json:"body_line_count"`
	BodyPreview         string             `json:"body_preview"`
}

func (q *Queries) ListProxyACLListsSummary(ctx context.Context) ([]ListProxyACLListsSummaryRow, error) {
	rows, err := q.db.Query(ctx, listProxyACLListsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyACLListsSummaryRow{}
	for rows.Next() {
		var i ListProxyACLListsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListType,
			&i.SourceMode,
			&i.SourceUrl,
			&i.PollIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyLineCount,
			&i.BodyPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxyACLListBody = `-- name: UpdateProxyACLListBody :one
UPDATE proxy_acl_lists
SET body = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, list_type, body, source_mode, source_url, poll_interval_minutes, created_at, updated_at
`

type UpdateProxyACLListBodyParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateProxyACLListBody(ctx context.Context, arg UpdateProxyACLListBodyParams) (ProxyAclList, error) {
	row := q.db.QueryRow(ctx, updateProxyACLListBody, arg.ID, arg.Body)
	var i ProxyAclList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListType,
		&i.Body,
		&i.SourceMode,
		&i.SourceUrl,
		&i.PollIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProxyACLList = `-- name: UpsertProxyACLList :one
INSERT INTO proxy_acl_lists (id, name, list_type, body, source_mode, source_url, poll_interval_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (name) DO UPDATE
SET
    list_type = EXCLUDED.list_type,
    body = EXCLUDED.body,
    source_mode = EXCLUDED.source_mode,
    source_url = EXCLUDED.source_url,
    poll_interval_minutes = EXCLUDED.poll_interval_minutes,
    updated_at = now()
RETURNING id, name, list_type, body, source_mode, source_url, poll_interval_minutes, created_at, updated_at
`

type UpsertProxyACLListParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	ListType            string    `json:"list_type"`
	Body                string    `json:"body"`
	SourceMode          string    `json:"source_mode"`
	SourceUrl           string    `json:"source_url"`
	PollIntervalMinutes int32     `json:"poll_interval_minutes"`
}

func (q *Queries) UpsertProxyACLList(ctx context.Context, arg UpsertProxyACLListParams) (ProxyAclList, error) {
	row := q.db.QueryRow(ctx, upsertProxyACLList,
		arg.ID,
		arg.Name,
		arg.ListType,
		arg.Body,
		arg.SourceMode,
		arg.SourceUrl,
		arg.PollIntervalMinutes,
	)
	var i ProxyAclList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListType,
		&i.Body,
		&i.SourceMode,
		&i.SourceUrl,
		&i.PollIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
