// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getSettings = `-- name: GetSettings :one
SELECT id, access_log_retention_days, created_at, updated_at
FROM settings
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSettings = `-- name: InsertSettings :one
INSERT INTO settings (id, access_log_retention_days)
VALUES ($1, $2)
RETURNING id, access_log_retention_days, created_at, updated_at
`

type InsertSettingsParams struct {
	ID                     uuid.UUID `json:"id"`
	AccessLogRetentionDays int32     `json:"access_log_retention_days"`
}

func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, insertSettings, arg.ID, arg.AccessLogRetentionDays)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET
    access_log_retention_days = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, access_log_retention_days, created_at, updated_at
`

type UpdateSettingsParams struct {
	ID                     uuid.UUID `json:"id"`
	AccessLogRetentionDays int32     `json:"access_log_retention_days"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.ID, arg.AccessLogRetentionDays)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AccessLogRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
